### PR TITLE
Lps 161155 8 22 1

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @zhangyan0701 , Could you please help me check the test results ? Thanks!

**Comment by zhangyan0701** [comment]
There are some failures seem related.
Error occurs when open Configuration modal in some portlets. 

Example: [Search bar](https://testray.liferay.com/home/-/testray/case_results/1986107282)
before1

And error message in console:
```
[beanshell] 2022-09-22 04:18:50.077 ERROR [http-nio-8080-exec-9][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
[beanshell] 2022-09-22 04:18:50.078 ERROR [http-nio-8080-exec-9][PortletConfigurationPortlet:700] null
[beanshell] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
```
Other failed tests:
Custom Facet: https://testray.liferay.com/home/-/testray/case_results/1986107668
Search Results: https://testray.liferay.com/home/-/testray/case_results/1986107724
Message Boards: https://testray.liferay.com/home/-/testray/case_results/1986106885
Tag Cloud: https://testray.liferay.com/home/-/testray/case_results/1986107391

**Comment by W2jx** [comment]
@zhangyan0701 Thank you!

**Pull request closed without merging**
