### PR TITLE
LPS-X Convert method reference to ServiceTrackerMap

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when you free? Thanks!

**Comment by catarineaguiar** [comment]
@W2jx possible regressions:

```
     [exec] com.liferay.object.service.test.ObjectEntryLocalServiceSearchObjectEntriesTest > testBigDecimal STARTED
[beanshell] 2022-10-07 08:32:59.161 ERROR [Framework Event Dispatcher: Equinox Container: fde1628b-c096-42ac-98ec-a3af1c99f6c7][Framework:56] FrameworkEvent ERROR
[beanshell] java.lang.NullPointerException: null
[beanshell] 2022-10-07 08:32:59.212 ERROR [Framework Event Dispatcher: Equinox Container: fde1628b-c096-42ac-98ec-a3af1c99f6c7][Framework:56] FrameworkEvent ERROR
[beanshell] java.lang.NullPointerException: null
     [exec] 
     [exec] com.liferay.object.service.test.ObjectEntryLocalServiceSearchObjectEntriesTest > testBigDecimal FAILED
     [exec]     java.lang.AssertionError: Thread Thread[Framework Event Dispatcher: Equinox Container: fde1628b-c096-42ac-98ec-a3af1c99f6c7,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.Events.Framework, message=FrameworkEvent ERROR
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.Events.Framework, message=FrameworkEvent ERROR
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-31/test-portal-acceptance-pullrequest(master)/5347/modules-integration-mysql57-jdk8/0/3/jenkins-console.txt.gz?authuser=0)

**Pull request closed without merging**
