### PR TITLE
Lps test properties 10 7 1

### PR DESCRIPTION
**Pull request by W2jx**

### CODE REVIEW

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
ci:test:sf

**Comment by W2jx** [comment]
ci:test:relevant

**Comment by W2jx** [comment]
Hi @catarineaguiar , Could you please help me check the test results when you free? Thanks!

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
@W2jx functional tests failed:

```
[beanshell] 2022-10-07 21:47:15.828 ERROR [Start Level: Equinox Container: b1a739b8-702f-4613-925e-34e951d86cfc][IndexerRequestBufferExecutorWatcher:56] bundle com.liferay.portal.search:8.0.45 (215)[com.liferay.portal.search.internal.buffer.IndexerRequestBufferExecutorWatcher(357)] : The activate method has thrown an exception
[beanshell] java.lang.IllegalArgumentException: The property "buffered.execution.mode" is invalid for java.lang.String
[beanshell] 	at com.liferay.portal.search.internal.buffer.IndexerRequestBufferExecutorWatcher._getBufferedExecutionMode(IndexerRequestBufferExecutorWatcher.java:94) ~[?:?]
[beanshell] 	at com.liferay.portal.search.internal.buffer.IndexerRequestBufferExecutorWatcher.lambda$activate$0(IndexerRequestBufferExecutorWatcher.java:79) ~[?:?]
[beanshell] 	at com.liferay.osgi.service.tracker.collections.map.ServiceReferenceMapperFactory.lambda$create$0(ServiceReferenceMapperFactory.java:35) ~[com.liferay.osgi.service.tracker.collections.jar:?]
[beanshell] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:241) ~[com.liferay.osgi.service.tracker.collections.jar:?]
[beanshell] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:229) ~[com.liferay.osgi.service.tracker.collections.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
[beanshell] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
```
full log [here](https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/736/functional-tomcat90-mysql57-jdk8/1/5/jenkins-console.txt.gz?authuser=0)

**Comment by W2jx** [comment]
ci:test:relevant

**Pull request closed without merging**
